/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  AngularJS,
  Cpp,
  Csharp,
  ExpressJS,
  Java,
  JavaScript,
  Laravel,
  MongoDB,
  MySQL,
  NestJS,
  NextJS,
  NodeJS,
  PHP,
  PostgreSQL,
  Python,
  ReactIcon,
  SpringBoot,
  TypeScript,
} from "@/components/icons/skills/icons";
import {
  IconBrandAzure,
  IconBrandCloudflare,
  IconBrandDjango,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandFirebase,
  IconBrandGraphql,
  IconBrandPrisma,
  IconBrandRedux,
  IconBrandSupabase,
  IconBrandVercel,
} from "@tabler/icons-react";

export const AboutContent = {
  SE1: {
    title: {
      line1: "Innovator. Entrepreneur.",
      line2: "Software Engineer.",
    },
    description:
      "Hello, I'm Sahan Sachintha, a full-stack software engineer dedicated to crafting exceptional digital experiences. With expertise in both front-end and back-end development, I bring your ideas to life through innovative software solutions. Feel free to get in touch, and let's create something amazing together.land let's create something amazing",
  },

  bento: {
    B1: {
      title: "Who I Am",
      description:
        "I'm Sahan Sachintha, a passionate Full-Stack Software Engineer and Entrepreneur. I specialize in blending creativity with cutting-edge technology to build innovative solutions. My mission is to bring impactful changes through software and strategic leadership.",
    },
  },

  KB: {
    title: "Skillset Overview",
    description: "Areas of Expertise and Technical Proficiency",
    skills: {
      dev: [
        {
          title: "Java",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: Java,
        },
        {
          title: "C#",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-cyan-800", light: "bg-cyan-600" },
          icon: Csharp,
        },
        // {
        //   title: "C++",
        //   colors: [252, 125, 125],
        //   bgColors: { dark: "dark:bg-cyan-800", light: "bg-cyan-600" },
        //   icon: Cpp,
        // },
        {
          title: "Python",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: Python,
        },
        {
          title: "JavaScript",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: JavaScript,
        },
        {
          title: "TypeScript",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: TypeScript,
        },
        {
          title: "NodeJS",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: NodeJS,
        },
        {
          title: "React",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: ReactIcon,
        },
        {
          title: "NextJS",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: NextJS,
        },
        {
          title: "NestJS",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: NestJS,
        },
        {
          title: "PHP",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: PHP,
        },
        // {
        //   title: "Laravel",
        //   colors: [252, 125, 125],
        //   bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
        //   icon: Laravel,
        // },
        {
          title: "Spring Boot",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: SpringBoot,
        },
        {
          title: "Angular",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: AngularJS,
        },
        {
          title: "ExpressJS",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: ExpressJS,
        },
        {
          title: "PostgreSQL",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: PostgreSQL,
        },
        {
          title: "MySQL",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: MySQL,
        },
        {
          title: "MongoDB",
          colors: [252, 125, 125],
          bgColors: { dark: "dark:bg-red-800", light: "bg-red-600" },
          icon: MongoDB,
        },
        {
          title: "Redux",
          colors: [124, 58, 237],
          bgColors: { dark: "dark:bg-violet-800", light: "bg-violet-600" },
          icon: IconBrandRedux,
          variant: "stroke",
        },
        {
          title: "Django",
          colors: [10, 60, 20],
          bgColors: { dark: "dark:bg-emerald-900", light: "bg-emerald-700" },
          icon: IconBrandDjango,
          variant: "stroke",
        },
        {
          title: "Docker",
          colors: [37, 150, 237],
          bgColors: { dark: "dark:bg-sky-800", light: "bg-sky-600" },
          icon: IconBrandDocker,
          variant: "stroke",
        },
        {
          title: "GraphQL",
          colors: [230, 30, 122],
          bgColors: { dark: "dark:bg-pink-800", light: "bg-pink-600" },
          icon: IconBrandGraphql,
          variant: "stroke",
        },
        {
          title: "Prisma",
          colors: [50, 50, 55],
          bgColors: { dark: "dark:bg-slate-800", light: "bg-slate-600" },
          icon: IconBrandPrisma,
          variant: "stroke",
        },
        {
          title: "Firebase",
          colors: [255, 172, 0],
          bgColors: { dark: "dark:bg-amber-800", light: "bg-amber-600" },
          icon: IconBrandFirebase,
          variant: "stroke",
        },
        {
          title: "Supabase",
          colors: [62, 207, 142],
          bgColors: { dark: "dark:bg-green-800", light: "bg-green-600" },
          icon: IconBrandSupabase,
          variant: "stroke",
        },
        {
          title: "Vercel",
          colors: [0, 0, 0],
          bgColors: { dark: "dark:bg-neutral-800", light: "bg-neutral-700" },
          icon: IconBrandVercel,
          variant: "stroke",
        },
        {
          title: "Cloudflare",
          colors: [243, 128, 32],
          bgColors: { dark: "dark:bg-orange-800", light: "bg-orange-600" },
          icon: IconBrandCloudflare,
          variant: "stroke",
        },
        {
          title: "Azure",
          colors: [0, 120, 212],
          bgColors: { dark: "dark:bg-blue-800", light: "bg-blue-600" },
          icon: IconBrandAzure,
          variant: "stroke",
        },
        {
          title: "Figma",
          colors: [242, 78, 30],
          bgColors: { dark: "dark:bg-orange-800", light: "bg-orange-600" },
          icon: IconBrandFigma,
          variant: "stroke",
        },
      ],
    },
  },
};
