import {
  AWS,
  ActiveListening,
  Adaptability,
  AngularJS,
  BootstrapIcon,
  CSS,
  Coaching,
  Collaboration,
  Communication,
  Cpp,
  Csharp,
  DotNET,
  Empathy,
  Excel,
  ExpressJS,
  FeedbackDelivery,
  Flutter,
  Golang,
  GoogleAnalytics,
  GoogleCloud,
  HTML,
  Illustrator,
  InVision,
  Ionic,
  JQuery,
  Java,
  JavaScript,
  Keras,
  Kotlin,
  Kubernetes,
  MongoDB,
  Motivation,
  MySQL,
  NestJS,
  NextJS,
  NodeJS,
  OpenAI,
  PHP,
  Photoshop,
  PostgreSQL,
  PowerBI,
  ProblemSolving,
  PyTorch,
  Python,
  ReactIcon,
  RubyOnRails,
  Rust,
  SASS,
  SQLite,
  Sketch,
  SpringBoot,
  Swift,
  Tableau,
  TailwindCSS,
  TensorFlow,
  Terraform,
  TimeManagement,
  TypeScript,
  VueJS,
  XD,
  Xamarin,
} from "@/components/icons/skills/icons";
import {
  IconBrandAzure,
  IconBrandCloudflare,
  IconBrandDjango,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandFirebase,
  IconBrandGraphql,
  IconBrandPrisma,
  IconBrandRedux,
  IconBrandSupabase,
  IconBrandVercel,
} from "@tabler/icons-react";
import type { SkillCategory } from "@/types/skills";

// Categories follow the neth about page. Proficiency levels are
// intentionally not included: none are claimed elsewhere on the site.
const categories: SkillCategory[] = [
  {
    id: "SC1",
    category: "Web Development",
    skills: [
      {
        name: "HTML",
        abbr: "HTML",
        type: "frontend",
        baseColor: { light: "#F1E05A", dark: "#E44D26" },
        icon: HTML,
      },
      {
        name: "CSS",
        abbr: "CSS",
        type: "frontend",
        baseColor: { light: "#563D7C", dark: "#1572B6" },
        icon: CSS,
      },
      {
        name: "JavaScript",
        abbr: "JS",
        type: "language",
        baseColor: { light: "#B59B00", dark: "#F7DF1E" },
        icon: JavaScript,
      },
      {
        name: "React",
        abbr: "React",
        type: "frontend",
        baseColor: { light: "#087EA4", dark: "#61DAFB" },
        icon: ReactIcon,
      },
      {
        name: "Next.js",
        abbr: "Next",
        type: "frontend",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        icon: NextJS,
      },
      {
        name: "TypeScript",
        abbr: "TS",
        type: "language",
        baseColor: { light: "#3178C6", dark: "#4A9BE8" },
        icon: TypeScript,
      },
      {
        name: "jQuery",
        abbr: "jQ",
        type: "frontend",
        baseColor: { light: "#0769AD", dark: "#0868AC" },
        icon: JQuery,
      },
      {
        name: "Tailwind CSS",
        abbr: "TwCSS",
        type: "frontend",
        baseColor: { light: "#06B6D4", dark: "#4FD1C5" },
        icon: TailwindCSS,
      },
      {
        name: "Bootstrap",
        abbr: "BS",
        type: "frontend",
        baseColor: { light: "#563D7C", dark: "#7952B3" },
        icon: BootstrapIcon,
      },
      {
        name: "Sass/SCSS",
        abbr: "Sass",
        type: "frontend",
        baseColor: { light: "#CC6699", dark: "#C69" },
        icon: SASS,
      },
      {
        name: "GraphQL",
        abbr: "GQL",
        type: "api",
        baseColor: { light: "#C4007F", dark: "#E535AB" },
        icon: IconBrandGraphql,
        variant: "stroke",
      },
      {
        name: "Vue.js",
        abbr: "Vue",
        type: "framework",
        baseColor: { light: "#42b883", dark: "#35495e" },
        icon: VueJS,
      },
      {
        name: "Express",
        abbr: "Exp",
        type: "backend",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        icon: ExpressJS,
      },
      {
        name: "Angular",
        abbr: "NG",
        type: "frontend",
        baseColor: { light: "#DD0031", dark: "#F5476B" },
        icon: AngularJS,
      },
      {
        name: "Redux",
        abbr: "Redux",
        type: "frontend",
        baseColor: { light: "#764ABC", dark: "#A17FE0" },
        icon: IconBrandRedux,
        variant: "stroke",
      },
      {
        name: "NestJS",
        abbr: "Nest",
        type: "backend",
        baseColor: { light: "#E0234E", dark: "#F0587B" },
        icon: NestJS,
      },
    ],
  },
  {
    id: "SC2",
    category: "Mobile Development",
    skills: [
      {
        name: "React Native",
        abbr: "RN",
        type: "framework",
        baseColor: { light: "#61DBFB", dark: "#20232A" },
        icon: ReactIcon,
      },
      {
        name: "Flutter",
        abbr: "Flutter",
        type: "framework",
        baseColor: { light: "#02569B", dark: "#02569B" },
        icon: Flutter,
      },
      {
        name: "Swift",
        abbr: "Swift",
        type: "language",
        baseColor: { light: "#F05138", dark: "#F05138" },
        icon: Swift,
      },
      {
        name: "Kotlin",
        abbr: "Kotlin",
        type: "language",
        baseColor: { light: "#7F52FF", dark: "#7F52FF" },
        icon: Kotlin,
      },
      {
        name: "Ionic",
        abbr: "Ionic",
        type: "framework",
        baseColor: { light: "#3880ff", dark: "#3880ff" },
        icon: Ionic,
      },
      {
        name: "Xamarin",
        abbr: "Xamarin",
        type: "framework",
        baseColor: { light: "#0078D4", dark: "#0078D4" },
        icon: Xamarin,
      },
    ],
  },
  {
    id: "SC3",
    category: "Custom Software Development",
    skills: [
      {
        name: "Java",
        abbr: "Java",
        type: "language",
        baseColor: { light: "#E76F00", dark: "#F89820" },
        icon: Java,
      },
      {
        name: "Python",
        abbr: "Py",
        type: "language",
        baseColor: { light: "#3776AB", dark: "#FFD43B" },
        icon: Python,
      },
      {
        name: "C++",
        abbr: "C++",
        type: "language",
        baseColor: { light: "#00599C", dark: "#A8B9CC" },
        icon: Cpp,
      },
      {
        name: "Rust",
        abbr: "Rust",
        type: "language",
        baseColor: { light: "#000000", dark: "#000000" },
        icon: Rust,
      },
      {
        name: "Node.js",
        abbr: "Node",
        type: "backend",
        baseColor: { light: "#339933", dark: "#68A063" },
        icon: NodeJS,
      },
      {
        name: "Go (Golang)",
        abbr: "Go",
        type: "language",
        baseColor: { light: "#00ADD8", dark: "#00ADD8" },
        icon: Golang,
      },
      {
        name: ".NET Framework",
        abbr: ".NET",
        type: "framework",
        baseColor: { light: "#512BD4", dark: "#512BD4" },
        icon: DotNET,
      },
      {
        name: "Ruby on Rails",
        abbr: "RoR",
        type: "framework",
        baseColor: { light: "#CC0000", dark: "#D40000" },
        icon: RubyOnRails,
      },
      {
        name: "Spring Boot",
        abbr: "Spring",
        type: "backend",
        baseColor: { light: "#4E8F1F", dark: "#6DB33F" },
        icon: SpringBoot,
      },
      {
        name: "Django",
        abbr: "Dj",
        type: "backend",
        baseColor: { light: "#092E20", dark: "#44B78B" },
        icon: IconBrandDjango,
        variant: "stroke",
      },
      {
        name: "C#",
        abbr: "C#",
        type: "language",
        baseColor: { light: "#68217A", dark: "#B77FD0" },
        icon: Csharp,
      },
      {
        name: "PHP",
        abbr: "PHP",
        type: "language",
        baseColor: { light: "#777BB4", dark: "#8892BF" },
        icon: PHP,
      },
    ],
  },
  {
    id: "SC4",
    category: "UI/UX & Graphic Design",
    skills: [
      {
        name: "Adobe XD",
        abbr: "XD",
        type: "tool",
        baseColor: { light: "#FF61F6", dark: "#FF61F6" },
        icon: XD,
      },
      {
        name: "Figma",
        abbr: "Figma",
        type: "design",
        baseColor: { light: "#F24E1E", dark: "#FF7262" },
        icon: IconBrandFigma,
        variant: "stroke",
      },
      {
        name: "Sketch",
        abbr: "Sketch",
        type: "tool",
        baseColor: { light: "#F7B500", dark: "#F7B500" },
        icon: Sketch,
      },
      {
        name: "InVision",
        abbr: "InVision",
        type: "tool",
        baseColor: { light: "#FF5B24", dark: "#FF5B24" },
        icon: InVision,
      },
      {
        name: "Adobe Photoshop",
        abbr: "PS",
        type: "tool",
        baseColor: { light: "#31A8FF", dark: "#31A8FF" },
        icon: Photoshop,
      },
      {
        name: "Adobe Illustrator",
        abbr: "AI",
        type: "tool",
        baseColor: { light: "#FF9A00", dark: "#FF9A00" },
        icon: Illustrator,
      },
    ],
  },
  {
    id: "SC5",
    category: "DevOps & Cloud Services",
    skills: [
      {
        name: "Docker",
        abbr: "Docker",
        type: "tool",
        baseColor: { light: "#1D7FC7", dark: "#2496ED" },
        icon: IconBrandDocker,
        variant: "stroke",
      },
      {
        name: "Kubernetes",
        abbr: "K8s",
        type: "tool",
        baseColor: { light: "#326CE5", dark: "#326CE5" },
        icon: Kubernetes,
      },
      {
        name: "AWS",
        abbr: "AWS",
        type: "cloud",
        baseColor: { light: "#FF9900", dark: "#FF9900" },
        icon: AWS,
      },
      {
        name: "Azure",
        abbr: "Azure",
        type: "cloud",
        baseColor: { light: "#0078D4", dark: "#50A0E8" },
        icon: IconBrandAzure,
        variant: "stroke",
      },
      {
        name: "Google Cloud",
        abbr: "GCP",
        type: "cloud",
        baseColor: { light: "#4285F4", dark: "#4285F4" },
        icon: GoogleCloud,
      },
      {
        name: "Terraform",
        abbr: "Terraform",
        type: "tool",
        baseColor: { light: "#7B42B1", dark: "#7B42B1" },
        icon: Terraform,
      },
      {
        name: "Vercel",
        abbr: "Vercel",
        type: "cloud",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        icon: IconBrandVercel,
        variant: "stroke",
      },
      {
        name: "Cloudflare",
        abbr: "CF",
        type: "cloud",
        baseColor: { light: "#D9650A", dark: "#F38020" },
        icon: IconBrandCloudflare,
        variant: "stroke",
      },
    ],
  },
  {
    id: "SC6",
    category: "Database Management",
    skills: [
      {
        name: "MySQL",
        abbr: "MySQL",
        type: "database",
        baseColor: { light: "#00758F", dark: "#4EA3C7" },
        icon: MySQL,
      },
      {
        name: "PostgreSQL",
        abbr: "PG",
        type: "database",
        baseColor: { light: "#336791", dark: "#5E9BD1" },
        icon: PostgreSQL,
      },
      {
        name: "MongoDB",
        abbr: "Mongo",
        type: "database",
        baseColor: { light: "#3F8F40", dark: "#4DB33D" },
        icon: MongoDB,
      },
      {
        name: "SQLite",
        abbr: "SQLite",
        type: "database",
        baseColor: { light: "#003B57", dark: "#003B57" },
        icon: SQLite,
      },
      {
        name: "Firebase",
        abbr: "Fire",
        type: "data tools",
        baseColor: { light: "#D98200", dark: "#FFCA28" },
        icon: IconBrandFirebase,
        variant: "stroke",
      },
      {
        name: "Prisma",
        abbr: "Prisma",
        type: "data tools",
        baseColor: { light: "#0C344B", dark: "#7FA4C2" },
        icon: IconBrandPrisma,
        variant: "stroke",
      },
      {
        name: "Supabase",
        abbr: "Supa",
        type: "data tools",
        baseColor: { light: "#1F9D6A", dark: "#3ECF8E" },
        icon: IconBrandSupabase,
        variant: "stroke",
      },
    ],
  },
  {
    id: "SC7",
    category: "AI & Machine Learning",
    skills: [
      {
        name: "TensorFlow",
        abbr: "TF",
        type: "ai",
        baseColor: { light: "#FF6F00", dark: "#FF6F00" },
        icon: TensorFlow,
      },
      {
        name: "Keras",
        abbr: "Keras",
        type: "ai",
        baseColor: { light: "#D32F2F", dark: "#D32F2F" },
        icon: Keras,
      },
      {
        name: "PyTorch",
        abbr: "PyTorch",
        type: "ai",
        baseColor: { light: "#EE4C2C", dark: "#EE4C2C" },
        icon: PyTorch,
      },
      {
        name: "OpenAI",
        abbr: "OpenAI",
        type: "ai",
        baseColor: { light: "#00A9E0", dark: "#00A9E0" },
        icon: OpenAI,
      },
    ],
  },
  {
    id: "SC8",
    category: "Data Analysis",
    skills: [
      {
        name: "Excel",
        abbr: "Excel",
        type: "tool",
        baseColor: { light: "#217346", dark: "#217346" },
        icon: Excel,
      },
      {
        name: "Power BI",
        abbr: "PBI",
        type: "tool",
        baseColor: { light: "#F2C811", dark: "#F2C811" },
        icon: PowerBI,
      },
      {
        name: "Tableau",
        abbr: "Tableau",
        type: "tool",
        baseColor: { light: "#E24E1B", dark: "#E24E1B" },
        icon: Tableau,
      },
      {
        name: "Google Analytics",
        abbr: "GA",
        type: "tool",
        baseColor: { light: "#EA4335", dark: "#EA4335" },
        icon: GoogleAnalytics,
      },
    ],
  },
  {
    id: "SC9",
    category: "General Skills",
    skills: [
      {
        name: "Communication",
        abbr: "Comm",
        type: "soft skill",
        baseColor: { light: "#4CAF50", dark: "#388E3C" },
        icon: Communication,
      },
      {
        name: "Problem-Solving",
        abbr: "PS",
        type: "soft skill",
        baseColor: { light: "#2196F3", dark: "#1976D2" },
        icon: ProblemSolving,
      },
      {
        name: "Time Management",
        abbr: "TM",
        type: "soft skill",
        baseColor: { light: "#FF9800", dark: "#F57C00" },
        icon: TimeManagement,
      },
      {
        name: "Adaptability",
        abbr: "Adapt",
        type: "soft skill",
        baseColor: { light: "#9C27B0", dark: "#7B1FA2" },
        icon: Adaptability,
      },
      {
        name: "Collaboration",
        abbr: "Collab",
        type: "soft skill",
        baseColor: { light: "#3F51B5", dark: "#303F9F" },
        icon: Collaboration,
      },
    ],
  },
  {
    id: "SC10",
    category: "Mentoring Skills",
    skills: [
      {
        name: "Active Listening",
        abbr: "AL",
        type: "soft skill",
        baseColor: { light: "#8BC34A", dark: "#689F38" },
        icon: ActiveListening,
      },
      {
        name: "Feedback Delivery",
        abbr: "FD",
        type: "soft skill",
        baseColor: { light: "#FF5722", dark: "#D32F2F" },
        icon: FeedbackDelivery,
      },
      {
        name: "Coaching",
        abbr: "Coach",
        type: "soft skill",
        baseColor: { light: "#009688", dark: "#00796B" },
        icon: Coaching,
      },
      {
        name: "Motivation",
        abbr: "Motiv",
        type: "soft skill",
        baseColor: { light: "#FFEB3B", dark: "#FBC02D" },
        icon: Motivation,
      },
      {
        name: "Empathy",
        abbr: "Emp",
        type: "soft skill",
        baseColor: { light: "#E91E63", dark: "#C2185B" },
        icon: Empathy,
      },
    ],
  },
];

export const MySkills = {
  layoutFilter: {
    label: "View as",
    options: [
      { id: 1, name: "Tabs" },
      { id: 2, name: "Grid" },
    ],
  },
  tabs: { categories },
};
