import {
  AngularJS,
  Csharp,
  ExpressJS,
  Java,
  JavaScript,
  MongoDB,
  MySQL,
  NestJS,
  NextJS,
  NodeJS,
  PHP,
  PostgreSQL,
  Python,
  ReactIcon,
  SpringBoot,
  TypeScript,
} from "@/components/icons/skills/icons";
import {
  IconBrandAzure,
  IconBrandCloudflare,
  IconBrandDjango,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandFirebase,
  IconBrandGraphql,
  IconBrandPrisma,
  IconBrandRedux,
  IconBrandSupabase,
  IconBrandVercel,
} from "@tabler/icons-react";
import type { SkillCategory } from "@/types/skills";

// Same skills as `AboutContent.KB.skills.dev`, grouped by area for the tabbed
// view. Proficiency levels are intentionally not included: none are claimed
// elsewhere on the site.
const categories: SkillCategory[] = [
  {
    id: "SC1",
    category: "Languages",
    skills: [
      {
        name: "Java",
        abbr: "Java",
        type: "language",
        baseColor: { light: "#E76F00", dark: "#F89820" },
        icon: Java,
      },
      {
        name: "C#",
        abbr: "C#",
        type: "language",
        baseColor: { light: "#68217A", dark: "#B77FD0" },
        icon: Csharp,
      },
      {
        name: "Python",
        abbr: "Py",
        type: "language",
        baseColor: { light: "#3776AB", dark: "#FFD43B" },
        icon: Python,
      },
      {
        name: "JavaScript",
        abbr: "JS",
        type: "language",
        baseColor: { light: "#B59B00", dark: "#F7DF1E" },
        icon: JavaScript,
      },
      {
        name: "TypeScript",
        abbr: "TS",
        type: "language",
        baseColor: { light: "#3178C6", dark: "#4A9BE8" },
        icon: TypeScript,
      },
      {
        name: "PHP",
        abbr: "PHP",
        type: "language",
        baseColor: { light: "#777BB4", dark: "#8892BF" },
        icon: PHP,
      },
    ],
  },
  {
    id: "SC2",
    category: "Frontend",
    skills: [
      {
        name: "React",
        abbr: "React",
        type: "frontend",
        baseColor: { light: "#087EA4", dark: "#61DAFB" },
        icon: ReactIcon,
      },
      {
        name: "Next.js",
        abbr: "Next",
        type: "frontend",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        icon: NextJS,
      },
      {
        name: "Angular",
        abbr: "NG",
        type: "frontend",
        baseColor: { light: "#DD0031", dark: "#F5476B" },
        icon: AngularJS,
      },
      {
        name: "Redux",
        abbr: "Redux",
        type: "frontend",
        baseColor: { light: "#764ABC", dark: "#A17FE0" },
        icon: IconBrandRedux,
        variant: "stroke",
      },
    ],
  },
  {
    id: "SC3",
    category: "Backend",
    skills: [
      {
        name: "Node.js",
        abbr: "Node",
        type: "backend",
        baseColor: { light: "#339933", dark: "#68A063" },
        icon: NodeJS,
      },
      {
        name: "NestJS",
        abbr: "Nest",
        type: "backend",
        baseColor: { light: "#E0234E", dark: "#F0587B" },
        icon: NestJS,
      },
      {
        name: "Express",
        abbr: "Exp",
        type: "backend",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        icon: ExpressJS,
      },
      {
        name: "Spring Boot",
        abbr: "Spring",
        type: "backend",
        baseColor: { light: "#4E8F1F", dark: "#6DB33F" },
        icon: SpringBoot,
      },
      {
        name: "Django",
        abbr: "Dj",
        type: "backend",
        baseColor: { light: "#092E20", dark: "#44B78B" },
        icon: IconBrandDjango,
        variant: "stroke",
      },
      {
        name: "GraphQL",
        abbr: "GQL",
        type: "api",
        baseColor: { light: "#C4007F", dark: "#E535AB" },
        icon: IconBrandGraphql,
        variant: "stroke",
      },
    ],
  },
  {
    id: "SC4",
    category: "Databases",
    skills: [
      {
        name: "PostgreSQL",
        abbr: "PG",
        type: "database",
        baseColor: { light: "#336791", dark: "#5E9BD1" },
        icon: PostgreSQL,
      },
      {
        name: "MySQL",
        abbr: "MySQL",
        type: "database",
        baseColor: { light: "#00758F", dark: "#4EA3C7" },
        icon: MySQL,
      },
      {
        name: "MongoDB",
        abbr: "Mongo",
        type: "database",
        baseColor: { light: "#3F8F40", dark: "#4DB33D" },
        icon: MongoDB,
      },
      {
        name: "Prisma",
        abbr: "Prisma",
        type: "data tools",
        baseColor: { light: "#0C344B", dark: "#7FA4C2" },
        icon: IconBrandPrisma,
        variant: "stroke",
      },
      {
        name: "Firebase",
        abbr: "Fire",
        type: "data tools",
        baseColor: { light: "#D98200", dark: "#FFCA28" },
        icon: IconBrandFirebase,
        variant: "stroke",
      },
      {
        name: "Supabase",
        abbr: "Supa",
        type: "data tools",
        baseColor: { light: "#1F9D6A", dark: "#3ECF8E" },
        icon: IconBrandSupabase,
        variant: "stroke",
      },
    ],
  },
  {
    id: "SC5",
    category: "Cloud & DevOps",
    skills: [
      {
        name: "Vercel",
        abbr: "Vercel",
        type: "cloud",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        icon: IconBrandVercel,
        variant: "stroke",
      },
      {
        name: "Cloudflare",
        abbr: "CF",
        type: "cloud",
        baseColor: { light: "#D9650A", dark: "#F38020" },
        icon: IconBrandCloudflare,
        variant: "stroke",
      },
      {
        name: "Azure",
        abbr: "Azure",
        type: "cloud",
        baseColor: { light: "#0078D4", dark: "#50A0E8" },
        icon: IconBrandAzure,
        variant: "stroke",
      },
      {
        name: "Docker",
        abbr: "Docker",
        type: "tool",
        baseColor: { light: "#1D7FC7", dark: "#2496ED" },
        icon: IconBrandDocker,
        variant: "stroke",
      },
    ],
  },
  {
    id: "SC6",
    category: "Design",
    skills: [
      {
        name: "Figma",
        abbr: "Figma",
        type: "design",
        baseColor: { light: "#F24E1E", dark: "#FF7262" },
        icon: IconBrandFigma,
        variant: "stroke",
      },
    ],
  },
];

export const MySkills = {
  layoutFilter: {
    label: "View as",
    options: [
      { id: 1, name: "Tabs" },
      { id: 2, name: "Grid" },
    ],
  },
  tabs: { categories },
};
