import {
  IconBrandAzure,
  IconBrandCloudflare,
  IconBrandDjango,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandFirebase,
  IconBrandGraphql,
  IconBrandPrisma,
  IconBrandRedux,
  IconBrandSupabase,
  IconBrandVercel,
} from "@tabler/icons-react";
import type { SkillCategory } from "@/types/skills";

// Categories follow the neth about page. Proficiency levels are
// intentionally not included: none are claimed elsewhere on the site.
const categories: SkillCategory[] = [
  {
    id: "SC1",
    category: "Web Development",
    skills: [
      {
        name: "HTML",
        abbr: "HTML",
        type: "frontend",
        baseColor: { light: "#F1E05A", dark: "#E44D26" },
        iconSrc: "/icons/skills/html.svg",
      },
      {
        name: "CSS",
        abbr: "CSS",
        type: "frontend",
        baseColor: { light: "#563D7C", dark: "#1572B6" },
        iconSrc: "/icons/skills/css.svg",
      },
      {
        name: "JavaScript",
        abbr: "JS",
        type: "language",
        baseColor: { light: "#B59B00", dark: "#F7DF1E" },
        iconSrc: "/icons/skills/javascript.svg",
      },
      {
        name: "React",
        abbr: "React",
        type: "frontend",
        baseColor: { light: "#087EA4", dark: "#61DAFB" },
        iconSrc: "/icons/skills/react.svg",
      },
      {
        name: "Next.js",
        abbr: "Next",
        type: "frontend",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        iconSrc: "/icons/skills/nextjs.svg",
      },
      {
        name: "TypeScript",
        abbr: "TS",
        type: "language",
        baseColor: { light: "#3178C6", dark: "#4A9BE8" },
        iconSrc: "/icons/skills/typescript.svg",
      },
      {
        name: "jQuery",
        abbr: "jQ",
        type: "frontend",
        baseColor: { light: "#0769AD", dark: "#0868AC" },
        iconSrc: "/icons/skills/jquery.svg",
      },
      {
        name: "Tailwind CSS",
        abbr: "TwCSS",
        type: "frontend",
        baseColor: { light: "#06B6D4", dark: "#4FD1C5" },
        iconSrc: "/icons/skills/tailwindcss.svg",
      },
      {
        name: "Bootstrap",
        abbr: "BS",
        type: "frontend",
        baseColor: { light: "#563D7C", dark: "#7952B3" },
        iconSrc: "/icons/skills/bootstrap.svg",
      },
      {
        name: "Sass/SCSS",
        abbr: "Sass",
        type: "frontend",
        baseColor: { light: "#CC6699", dark: "#C69" },
        iconSrc: "/icons/skills/sass.svg",
      },
      {
        name: "GraphQL",
        abbr: "GQL",
        type: "api",
        baseColor: { light: "#C4007F", dark: "#E535AB" },
        icon: IconBrandGraphql,
        variant: "stroke",
      },
      {
        name: "Vue.js",
        abbr: "Vue",
        type: "framework",
        baseColor: { light: "#42b883", dark: "#35495e" },
        iconSrc: "/icons/skills/vuejs.svg",
      },
      {
        name: "Express",
        abbr: "Exp",
        type: "backend",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        iconSrc: "/icons/skills/expressjs.svg",
      },
      {
        name: "Angular",
        abbr: "NG",
        type: "frontend",
        baseColor: { light: "#DD0031", dark: "#F5476B" },
        iconSrc: "/icons/skills/angularjs.svg",
      },
      {
        name: "Redux",
        abbr: "Redux",
        type: "frontend",
        baseColor: { light: "#764ABC", dark: "#A17FE0" },
        icon: IconBrandRedux,
        variant: "stroke",
      },
      {
        name: "NestJS",
        abbr: "Nest",
        type: "backend",
        baseColor: { light: "#E0234E", dark: "#F0587B" },
        iconSrc: "/icons/skills/nestjs.svg",
      },
    ],
  },
  {
    id: "SC2",
    category: "Mobile Development",
    skills: [
      {
        name: "React Native",
        abbr: "RN",
        type: "framework",
        baseColor: { light: "#61DBFB", dark: "#20232A" },
        iconSrc: "/icons/skills/react.svg",
      },
      {
        name: "Flutter",
        abbr: "Flutter",
        type: "framework",
        baseColor: { light: "#02569B", dark: "#02569B" },
        iconSrc: "/icons/skills/flutter.svg",
      },
      {
        name: "Swift",
        abbr: "Swift",
        type: "language",
        baseColor: { light: "#F05138", dark: "#F05138" },
        iconSrc: "/icons/skills/swift.svg",
      },
      {
        name: "Kotlin",
        abbr: "Kotlin",
        type: "language",
        baseColor: { light: "#7F52FF", dark: "#7F52FF" },
        iconSrc: "/icons/skills/kotlin.svg",
      },
      {
        name: "Ionic",
        abbr: "Ionic",
        type: "framework",
        baseColor: { light: "#3880ff", dark: "#3880ff" },
        iconSrc: "/icons/skills/ionic.svg",
      },
      {
        name: "Xamarin",
        abbr: "Xamarin",
        type: "framework",
        baseColor: { light: "#0078D4", dark: "#0078D4" },
        iconSrc: "/icons/skills/xamarin.svg",
      },
    ],
  },
  {
    id: "SC3",
    category: "Custom Software Development",
    skills: [
      {
        name: "Java",
        abbr: "Java",
        type: "language",
        baseColor: { light: "#E76F00", dark: "#F89820" },
        iconSrc: "/icons/skills/java.svg",
      },
      {
        name: "Python",
        abbr: "Py",
        type: "language",
        baseColor: { light: "#3776AB", dark: "#FFD43B" },
        iconSrc: "/icons/skills/python.svg",
      },
      {
        name: "C++",
        abbr: "C++",
        type: "language",
        baseColor: { light: "#00599C", dark: "#A8B9CC" },
        iconSrc: "/icons/skills/cpp.svg",
      },
      {
        name: "Rust",
        abbr: "Rust",
        type: "language",
        baseColor: { light: "#000000", dark: "#000000" },
        iconSrc: "/icons/skills/rust.svg",
      },
      {
        name: "Node.js",
        abbr: "Node",
        type: "backend",
        baseColor: { light: "#339933", dark: "#68A063" },
        iconSrc: "/icons/skills/nodejs.svg",
      },
      {
        name: "Go (Golang)",
        abbr: "Go",
        type: "language",
        baseColor: { light: "#00ADD8", dark: "#00ADD8" },
        iconSrc: "/icons/skills/golang.svg",
      },
      {
        name: ".NET Framework",
        abbr: ".NET",
        type: "framework",
        baseColor: { light: "#512BD4", dark: "#512BD4" },
        iconSrc: "/icons/skills/dotnet.svg",
      },
      {
        name: "Ruby on Rails",
        abbr: "RoR",
        type: "framework",
        baseColor: { light: "#CC0000", dark: "#D40000" },
        iconSrc: "/icons/skills/rubyonrails.svg",
      },
      {
        name: "Spring Boot",
        abbr: "Spring",
        type: "backend",
        baseColor: { light: "#4E8F1F", dark: "#6DB33F" },
        iconSrc: "/icons/skills/springboot.svg",
      },
      {
        name: "Django",
        abbr: "Dj",
        type: "backend",
        baseColor: { light: "#092E20", dark: "#44B78B" },
        icon: IconBrandDjango,
        variant: "stroke",
      },
      {
        name: "C#",
        abbr: "C#",
        type: "language",
        baseColor: { light: "#68217A", dark: "#B77FD0" },
        iconSrc: "/icons/skills/csharp.svg",
      },
      {
        name: "PHP",
        abbr: "PHP",
        type: "language",
        baseColor: { light: "#777BB4", dark: "#8892BF" },
        iconSrc: "/icons/skills/php.svg",
      },
    ],
  },
  {
    id: "SC4",
    category: "UI/UX & Graphic Design",
    skills: [
      {
        name: "Adobe XD",
        abbr: "XD",
        type: "tool",
        baseColor: { light: "#FF61F6", dark: "#FF61F6" },
        iconSrc: "/icons/skills/xd.svg",
      },
      {
        name: "Figma",
        abbr: "Figma",
        type: "design",
        baseColor: { light: "#F24E1E", dark: "#FF7262" },
        icon: IconBrandFigma,
        variant: "stroke",
      },
      {
        name: "Sketch",
        abbr: "Sketch",
        type: "tool",
        baseColor: { light: "#F7B500", dark: "#F7B500" },
        iconSrc: "/icons/skills/sketch.svg",
      },
      {
        name: "InVision",
        abbr: "InVision",
        type: "tool",
        baseColor: { light: "#FF5B24", dark: "#FF5B24" },
        iconSrc: "/icons/skills/invision.svg",
      },
      {
        name: "Adobe Photoshop",
        abbr: "PS",
        type: "tool",
        baseColor: { light: "#31A8FF", dark: "#31A8FF" },
        iconSrc: "/icons/skills/photoshop.svg",
      },
      {
        name: "Adobe Illustrator",
        abbr: "AI",
        type: "tool",
        baseColor: { light: "#FF9A00", dark: "#FF9A00" },
        iconSrc: "/icons/skills/illustrator.svg",
      },
    ],
  },
  {
    id: "SC5",
    category: "DevOps & Cloud Services",
    skills: [
      {
        name: "Docker",
        abbr: "Docker",
        type: "tool",
        baseColor: { light: "#1D7FC7", dark: "#2496ED" },
        icon: IconBrandDocker,
        variant: "stroke",
      },
      {
        name: "Kubernetes",
        abbr: "K8s",
        type: "tool",
        baseColor: { light: "#326CE5", dark: "#326CE5" },
        iconSrc: "/icons/skills/kubernetes.svg",
      },
      {
        name: "AWS",
        abbr: "AWS",
        type: "cloud",
        baseColor: { light: "#FF9900", dark: "#FF9900" },
        iconSrc: "/icons/skills/aws.svg",
      },
      {
        name: "Azure",
        abbr: "Azure",
        type: "cloud",
        baseColor: { light: "#0078D4", dark: "#50A0E8" },
        icon: IconBrandAzure,
        variant: "stroke",
      },
      {
        name: "Google Cloud",
        abbr: "GCP",
        type: "cloud",
        baseColor: { light: "#4285F4", dark: "#4285F4" },
        iconSrc: "/icons/skills/googlecloud.svg",
      },
      {
        name: "Terraform",
        abbr: "Terraform",
        type: "tool",
        baseColor: { light: "#7B42B1", dark: "#7B42B1" },
        iconSrc: "/icons/skills/terraform.svg",
      },
      {
        name: "Vercel",
        abbr: "Vercel",
        type: "cloud",
        baseColor: { light: "#000000", dark: "#FFFFFF" },
        icon: IconBrandVercel,
        variant: "stroke",
      },
      {
        name: "Cloudflare",
        abbr: "CF",
        type: "cloud",
        baseColor: { light: "#D9650A", dark: "#F38020" },
        icon: IconBrandCloudflare,
        variant: "stroke",
      },
    ],
  },
  {
    id: "SC6",
    category: "Database Management",
    skills: [
      {
        name: "MySQL",
        abbr: "MySQL",
        type: "database",
        baseColor: { light: "#00758F", dark: "#4EA3C7" },
        iconSrc: "/icons/skills/mysql.svg",
      },
      {
        name: "PostgreSQL",
        abbr: "PG",
        type: "database",
        baseColor: { light: "#336791", dark: "#5E9BD1" },
        iconSrc: "/icons/skills/postgresql.svg",
      },
      {
        name: "MongoDB",
        abbr: "Mongo",
        type: "database",
        baseColor: { light: "#3F8F40", dark: "#4DB33D" },
        iconSrc: "/icons/skills/mongodb.svg",
      },
      {
        name: "SQLite",
        abbr: "SQLite",
        type: "database",
        baseColor: { light: "#003B57", dark: "#003B57" },
        iconSrc: "/icons/skills/sqlite.svg",
      },
      {
        name: "Firebase",
        abbr: "Fire",
        type: "data tools",
        baseColor: { light: "#D98200", dark: "#FFCA28" },
        icon: IconBrandFirebase,
        variant: "stroke",
      },
      {
        name: "Prisma",
        abbr: "Prisma",
        type: "data tools",
        baseColor: { light: "#0C344B", dark: "#7FA4C2" },
        icon: IconBrandPrisma,
        variant: "stroke",
      },
      {
        name: "Supabase",
        abbr: "Supa",
        type: "data tools",
        baseColor: { light: "#1F9D6A", dark: "#3ECF8E" },
        icon: IconBrandSupabase,
        variant: "stroke",
      },
    ],
  },
  {
    id: "SC7",
    category: "AI & Machine Learning",
    skills: [
      {
        name: "TensorFlow",
        abbr: "TF",
        type: "ai",
        baseColor: { light: "#FF6F00", dark: "#FF6F00" },
        iconSrc: "/icons/skills/tensorflow.svg",
      },
      {
        name: "Keras",
        abbr: "Keras",
        type: "ai",
        baseColor: { light: "#D32F2F", dark: "#D32F2F" },
        iconSrc: "/icons/skills/keras.svg",
      },
      {
        name: "PyTorch",
        abbr: "PyTorch",
        type: "ai",
        baseColor: { light: "#EE4C2C", dark: "#EE4C2C" },
        iconSrc: "/icons/skills/pytorch.svg",
      },
      {
        name: "OpenAI",
        abbr: "OpenAI",
        type: "ai",
        baseColor: { light: "#00A9E0", dark: "#00A9E0" },
        iconSrc: "/icons/skills/openai.svg",
      },
    ],
  },
  {
    id: "SC8",
    category: "Data Analysis",
    skills: [
      {
        name: "Excel",
        abbr: "Excel",
        type: "tool",
        baseColor: { light: "#217346", dark: "#217346" },
        iconSrc: "/icons/skills/excel.svg",
      },
      {
        name: "Power BI",
        abbr: "PBI",
        type: "tool",
        baseColor: { light: "#F2C811", dark: "#F2C811" },
        iconSrc: "/icons/skills/powerbi.svg",
      },
      {
        name: "Tableau",
        abbr: "Tableau",
        type: "tool",
        baseColor: { light: "#E24E1B", dark: "#E24E1B" },
        iconSrc: "/icons/skills/tableau.svg",
      },
      {
        name: "Google Analytics",
        abbr: "GA",
        type: "tool",
        baseColor: { light: "#EA4335", dark: "#EA4335" },
        iconSrc: "/icons/skills/googleanalytics.svg",
      },
    ],
  },
  {
    id: "SC9",
    category: "General Skills",
    skills: [
      {
        name: "Communication",
        abbr: "Comm",
        type: "soft skill",
        baseColor: { light: "#4CAF50", dark: "#388E3C" },
        iconSrc: "/icons/skills/communication.svg",
      },
      {
        name: "Problem-Solving",
        abbr: "PS",
        type: "soft skill",
        baseColor: { light: "#2196F3", dark: "#1976D2" },
        iconSrc: "/icons/skills/problemsolving.svg",
      },
      {
        name: "Time Management",
        abbr: "TM",
        type: "soft skill",
        baseColor: { light: "#FF9800", dark: "#F57C00" },
        iconSrc: "/icons/skills/timemanagement.svg",
      },
      {
        name: "Adaptability",
        abbr: "Adapt",
        type: "soft skill",
        baseColor: { light: "#9C27B0", dark: "#7B1FA2" },
        iconSrc: "/icons/skills/adaptability.svg",
      },
      {
        name: "Collaboration",
        abbr: "Collab",
        type: "soft skill",
        baseColor: { light: "#3F51B5", dark: "#303F9F" },
        iconSrc: "/icons/skills/collaboration.svg",
      },
    ],
  },
  {
    id: "SC10",
    category: "Mentoring Skills",
    skills: [
      {
        name: "Active Listening",
        abbr: "AL",
        type: "soft skill",
        baseColor: { light: "#8BC34A", dark: "#689F38" },
        iconSrc: "/icons/skills/activelistening.svg",
      },
      {
        name: "Feedback Delivery",
        abbr: "FD",
        type: "soft skill",
        baseColor: { light: "#FF5722", dark: "#D32F2F" },
        iconSrc: "/icons/skills/feedbackdelivery.svg",
      },
      {
        name: "Coaching",
        abbr: "Coach",
        type: "soft skill",
        baseColor: { light: "#009688", dark: "#00796B" },
        iconSrc: "/icons/skills/coaching.svg",
      },
      {
        name: "Motivation",
        abbr: "Motiv",
        type: "soft skill",
        baseColor: { light: "#FFEB3B", dark: "#FBC02D" },
        iconSrc: "/icons/skills/motivation.svg",
      },
      {
        name: "Empathy",
        abbr: "Emp",
        type: "soft skill",
        baseColor: { light: "#E91E63", dark: "#C2185B" },
        iconSrc: "/icons/skills/empathy.svg",
      },
    ],
  },
];

export const MySkills = {
  layoutFilter: {
    label: "View as",
    options: [
      { id: 1, name: "Tabs" },
      { id: 2, name: "Grid" },
    ],
  },
  tabs: { categories },
};
