import { defineConfig } from "tsup";

// One entry per package.json `exports` subpath, each emitted at the same
// relative path under dist/ (e.g. src/security/ip.ts -> dist/security/ip.js
// + dist/security/ip.d.ts) so publishConfig.exports's dist paths line up
// exactly. ESM only (the package is "type": "module" and every consumer is
// Next.js/Node ESM-capable); node: builtins and every peer dependency
// (next, next-auth, react) stay external, never bundled.
export default defineConfig({
  entry: [
    "src/index.ts",
    "src/kit.ts",
    "src/authorize.ts",
    "src/config.ts",
    "src/next-auth-engine.ts",
    "src/better-auth/index.ts",
    "src/engines/next-auth.ts",
    "src/engines/next-auth-cookie.ts",
    "src/engines/better-auth.ts",
    "src/engines/better-auth-cookie.ts",
    "src/hono/index.ts",
    "src/user-agent.ts",
    "src/bootstrap.ts",
    "src/audit-event.ts",
    "src/session/index.ts",
    "src/session/core.ts",
    "src/rbac/index.ts",
    "src/rbac/rules.ts",
    "src/rbac/roles.ts",
    "src/mfa/index.ts",
    "src/security/index.ts",
    "src/cache/index.ts",
    "src/credentials.ts",
    "src/adapter.ts",
    "src/prisma/index.ts",
    "src/drizzle/index.ts",
    "src/password.ts",
    "src/password-policy.ts",
    "src/invite-token.ts",
    "src/safe-callback-url.ts",
    "src/short-link.ts",
    "src/short-link-path.ts",
    "src/constants.ts",
    "src/login-unlock.ts",
    "src/unlock-request.ts",
    "src/security/ip.ts",
    "src/security/allowlist.ts",
    "src/security/origin.ts",
    "src/security/csp.ts",
    "src/security/headers.ts",
    "src/security/scanner-paths.ts",
    "src/security/check-origin.ts",
    "src/security/request-device.ts",
    "src/security/device.ts",
    "src/cache/ratelimit.ts",
    "src/cache/memory.ts",
    "src/cache/redis.ts",
    "src/cli/index.ts",
  ],
  format: ["esm"],
  dts: { resolve: false },
  tsconfig: "tsconfig.build.json",
  outDir: "dist",
  // Shared modules go to chunks, so every subpath sees one copy of each class
  // and module-level state (instanceof and caches work across subpaths).
  splitting: true,
  sourcemap: false,
  clean: true,
  target: "es2022",
  platform: "node",
  external: ["next", "next-auth", "next-auth/providers/credentials", "next/server", "next/headers", "next/navigation", "react", "react-server-dom-webpack", "better-auth", "better-auth/api", "better-auth/next-js", "better-auth/adapters/prisma", "better-auth/db/adapter", "next-auth/jwt"],
  skipNodeModulesBundle: true,
});
